---
apiVersion: v1
kind: Namespace
metadata:
  name: kind-kind
---
apiVersion: clusterregistry.k8s.io/v1alpha1
kind: Cluster
metadata:
  labels:
    cloud: GCP
    name: kind-kind
    vendor: auto-detect
  name: kind-kind
  namespace: kind-kind
spec:
  authInfo: {}
  kubernetesApiEndpoints: {}
---
apiVersion: multicloud.ibm.com/v1alpha1
kind: EndpointConfig
metadata:
  name: kind-kind
  namespace: kind-kind
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  cisController:
    enabled: false
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  clusterName: kind-kind
  clusterNamespace: kind-kind
  iamPolicyController:
    enabled: true
  imageRegistry: quay.io/open-cluster-management
  policyController:
    enabled: true
  prometheusIntegration:
    enabled: true
  searchCollector:
    enabled: true
  serviceRegistry:
    dnsSuffix: mcm.svc
    enabled: true
    plugins: kube-service
  topologyCollector:
    enabled: true
    updateInterval: 15
  weaveCollector:
    enabled: false
  version: 1.0.0
---

