---
apiVersion: v1
kind: Namespace
metadata:
  name: sydney-cluster-2
---
apiVersion: clusterregistry.k8s.io/v1alpha1
kind: Cluster
metadata:
  labels:
    cloud: GCP
    name: sydney-cluster-2
    vendor: auto-detect
  name: sydney-cluster-2
  namespace: sydney-cluster-2
spec:
  authInfo: {}
  kubernetesApiEndpoints: {}
---
apiVersion: multicloud.ibm.com/v1alpha1
kind: EndpointConfig
metadata:
  name: sydney-cluster-2
  namespace: sydney-cluster-2
spec:
  applicationManager:
    enabled: true
  certPolicyController:
    enabled: true
  cisController:
    enabled: false
  clusterLabels:
    cloud: auto-detect
    vendor: auto-detect
  clusterName: sydney-cluster-2
  clusterNamespace: sydney-cluster-2
  iamPolicyController:
    enabled: true
  imageRegistry: quay.io/open-cluster-management
  policyController:
    enabled: true
  prometheusIntegration:
    enabled: true
  searchCollector:
    enabled: true
  serviceRegistry:
    dnsSuffix: mcm.svc
    enabled: true
    plugins: kube-service
  topologyCollector:
    enabled: true
    updateInterval: 15
  weaveCollector:
    enabled: false
  version: 1.0.0
---

