apiVersion: operators.open-cluster-management.io/v1beta1
kind: MultiClusterHub
metadata:
  name: multiclusterhub
  namespace: open-cluster-management
spec:
  imageRepository: "quay.io/open-cluster-management"
  imageTagSuffix: SNAPSHOT-2020-04-21-17-28-34
  imagePullPolicy: Always
  imagePullSecret: multiclusterhub-operator-pull-secret